# Global Variables
$terminal = kitty
$fileManager = dolphin
$menu = sh -c "if pgrep wofi; then killall wofi; else wofi --show drun; fi"
$mainMod = SUPER
$bar = sh -c "killall waybar || true; waybar -c ~/.config/waybar/config.jsonc &"

# Source
source = ~/.config/hypr/custom/monitors.conf
source = ~/.config/hypr/custom/hyprpaper.conf
source = ~/.config/hypr/custom/preload.conf
source = ~/.config/hypr/custom/environment.conf
source = ~/.config/hypr/custom/functions.conf
source = ~/.config/hypr/custom/rules.conf
source = ~/.config/hypr/custom/binds.conf