# Cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Set environment variables for GTK applications
env = GTK_THEME,Adwaita:dark
env = GTK2_RC_FILES,/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc

# For Qt applications
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORM,xcb
env = QT_STYLE_OVERRIDE,Adwaita-Dark

# Android
env = ANDROID_EMULATOR_USE_SYSTEM_LIBS,1
