# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrulev2 = center, floating:1, negative:class:^(Steam|Main)$

windowrulev2 = opacity 1.0 override, class:^(Emulator)$
windowrulev2 = noborder, class:^(Emulator)$
windowrulev2 = noblur, class:^(Emulator)$
windowrulev2 = noshadow, class:^(Emulator)$
windowrulev2 = group,class:^(Wine|Main)(.*)$

windowrulev2 = stayfocused, title:^(),class:^(steam)
windowrulev2 = minsize 1 1 , title:^(),class:^(steam)
